import numpy as np
import json
import os
from typing import List, Dict, Optional
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
import pickle

MODEL_PATH = os.path.join(os.path.dirname(__file__), "patch_priority_model.pkl")


class PatchPriorityPredictor:
    """
    ML model that predicts optimal patch ordering from CVE features,
    replacing the expensive 2,000-iteration Monte Carlo simulation
    with instant inference.

    Trained on synthetic data generated by running Monte Carlo simulations
    across diverse vulnerability scenarios. The model learns the relationship
    between CVE features and optimal patch position.
    """

    FEATURE_NAMES = [
        "cvss_score",
        "effective_score",
        "complexity_score",
        "estimated_patch_hours",
        "service_criticality",
        "compliance_relevant",
        "exploit_available",
        "prior_service_risk",
        "propagated_service_risk",
        "risk_multiplier",
        "num_cves_in_service",
        "relative_severity",
    ]

    def __init__(self):
        self.model = GradientBoostingRegressor(
            n_estimators=200,
            max_depth=5,
            learning_rate=0.1,
            subsample=0.8,
            random_state=42,
        )
        self.scaler = StandardScaler()
        self.is_trained = False

    def _extract_features(self, cve: dict, all_cves: List[dict]) -> np.ndarray:
        service = cve.get("affected_service", "")
        cves_in_service = sum(1 for c in all_cves if c.get("affected_service") == service)
        max_score = max((c.get("effective_score", 0) for c in all_cves), default=1)
        relative_severity = cve.get("effective_score", 0) / max(max_score, 0.01)

        return np.array([
            cve.get("cvss_score", 5.0),
            cve.get("effective_score", 5.0),
            cve.get("complexity_score", 5),
            cve.get("estimated_patch_hours", 2),
            cve.get("service_criticality", 5),
            float(cve.get("compliance_relevant", False)),
            float(cve.get("exploit_available", False)),
            cve.get("prior_service_risk", 0.5),
            cve.get("propagated_service_risk", 0.5),
            cve.get("risk_multiplier", 1.0),
            cves_in_service,
            relative_severity,
        ])

    def _generate_training_data(
        self, n_scenarios: int = 500, cves_per_scenario: int = 15
    ) -> tuple:
        from .monte_carlo import MonteCarloSimulator

        X_all, y_all = [], []

        for _ in range(n_scenarios):
            n_cves = np.random.randint(5, cves_per_scenario + 1)
            n_services = np.random.randint(2, max(3, n_cves // 3))
            services = [f"svc-{i}" for i in range(n_services)]

            cves = []
            for i in range(n_cves):
                svc = services[np.random.randint(0, n_services)]
                cvss = round(np.random.uniform(1.0, 10.0), 1)
                exploit = bool(np.random.random() < 0.3)
                compliance = bool(np.random.random() < 0.25)
                complexity = round(np.random.uniform(1, 10), 1)
                patch_hours = round(np.random.uniform(0.5, 8), 1)
                criticality = round(np.random.uniform(1, 10), 1)

                prior_risk = round(np.random.uniform(0.1, 0.95), 4)
                propagation_factor = np.random.uniform(1.0, 1.5)
                propagated_risk = round(min(prior_risk * propagation_factor, 1.0), 4)
                risk_mult = round(propagated_risk / max(prior_risk, 0.01), 4)
                effective = round(cvss * min(risk_mult, 1.5), 2)

                cves.append({
                    "cve_id": f"CVE-SYNTH-{_:04d}-{i:03d}",
                    "affected_service": svc,
                    "cvss_score": cvss,
                    "effective_score": effective,
                    "complexity_score": complexity,
                    "estimated_patch_hours": patch_hours,
                    "service_criticality": criticality,
                    "compliance_relevant": compliance,
                    "exploit_available": exploit,
                    "prior_service_risk": prior_risk,
                    "propagated_service_risk": propagated_risk,
                    "risk_multiplier": risk_mult,
                })

            sim = MonteCarloSimulator(cves, {}, n_iterations=500)
            results = sim.simulate()
            optimal_order = results["optimal_order"]

            position_map = {cve_id: pos for pos, cve_id in enumerate(optimal_order)}

            for cve in cves:
                features = self._extract_features(cve, cves)
                normalized_position = position_map[cve["cve_id"]] / max(len(cves) - 1, 1)
                X_all.append(features)
                y_all.append(normalized_position)

        return np.array(X_all), np.array(y_all)

    def train(self, n_scenarios: int = 500) -> dict:
        print(f"Generating training data from {n_scenarios} synthetic scenarios...")
        X, y = self._generate_training_data(n_scenarios=n_scenarios)

        split = int(len(X) * 0.8)
        indices = np.random.permutation(len(X))
        train_idx, val_idx = indices[:split], indices[split:]

        X_train, y_train = X[train_idx], y[train_idx]
        X_val, y_val = X[val_idx], y[val_idx]

        self.scaler.fit(X_train)
        X_train_scaled = self.scaler.transform(X_train)
        X_val_scaled = self.scaler.transform(X_val)

        print(f"Training on {len(X_train)} samples, validating on {len(X_val)}...")
        self.model.fit(X_train_scaled, y_train)
        self.is_trained = True

        train_score = self.model.score(X_train_scaled, y_train)
        val_score = self.model.score(X_val_scaled, y_val)

        val_pred = self.model.predict(X_val_scaled)
        mae = np.mean(np.abs(val_pred - y_val))

        importances = dict(zip(self.FEATURE_NAMES, self.model.feature_importances_))
        importances = dict(sorted(importances.items(), key=lambda x: x[1], reverse=True))

        metrics = {
            "train_r2": round(train_score, 4),
            "val_r2": round(val_score, 4),
            "val_mae": round(mae, 4),
            "n_train": len(X_train),
            "n_val": len(X_val),
            "feature_importances": {k: round(v, 4) for k, v in importances.items()},
        }

        print(f"Training complete. Val R2={val_score:.4f}, MAE={mae:.4f}")
        return metrics

    def predict_priority(self, scored_cves: List[dict]) -> List[dict]:
        if not self.is_trained:
            raise RuntimeError("Model not trained. Call train() or load() first.")

        features = np.array([self._extract_features(cve, scored_cves) for cve in scored_cves])
        features_scaled = self.scaler.transform(features)
        predicted_positions = self.model.predict(features_scaled)

        ranked = sorted(
            zip(scored_cves, predicted_positions),
            key=lambda x: x[1],
        )

        ordered_ids = [cve["cve_id"] for cve, _ in ranked]

        cumulative_risk = self._compute_cumulative_risk(ordered_ids, scored_cves)
        total_area = sum(cumulative_risk)

        naive_ordering = sorted(
            [c["cve_id"] for c in scored_cves],
            key=lambda cid: next(c["cvss_score"] for c in scored_cves if c["cve_id"] == cid),
            reverse=True,
        )
        naive_curve = self._compute_cumulative_risk(naive_ordering, scored_cves)
        naive_area = sum(naive_curve)
        improvement = round((naive_area - total_area) / naive_area * 100, 1) if naive_area > 0 else 0

        # Build confidence intervals (single-prediction: fixed position, full stability)
        confidence_intervals = {}
        for i, cve_id in enumerate(ordered_ids):
            confidence_intervals[cve_id] = {
                "median_position": i,
                "ci_low": i,
                "ci_high": i,
                "stability": 1.0,
            }

        return {
            "optimal_order": ordered_ids,
            "optimal_score": round(total_area, 2),
            "naive_score": round(naive_area, 2),
            "improvement_pct": improvement,
            "risk_curve": [
                {"step": i, "risk": round(r, 4)} for i, r in enumerate(cumulative_risk)
            ],
            "naive_curve": [
                {"step": i, "risk": round(r, 4)} for i, r in enumerate(naive_curve)
            ],
            "confidence_intervals": confidence_intervals,
            "iterations_run": 0,
            "method": "ml_predictor",
            "confidence_note": "Predicted via trained GradientBoosting model (instant inference)",
        }

    def _compute_cumulative_risk(self, ordering: List[str], cves: List[dict]) -> List[float]:
        cve_map = {c["cve_id"]: c for c in cves}
        total_risk = sum(c["effective_score"] for c in cves)
        curve = [total_risk]
        running = total_risk
        for cve_id in ordering:
            cve = cve_map[cve_id]
            running -= cve["effective_score"]
            time_penalty = cve.get("complexity_score", 5) / 100
            curve.append(max(0, running + time_penalty))
        return curve

    def save(self, path: str = MODEL_PATH):
        with open(path, "wb") as f:
            pickle.dump({"model": self.model, "scaler": self.scaler}, f)
        print(f"Model saved to {path}")

    def load(self, path: str = MODEL_PATH) -> bool:
        if not os.path.exists(path):
            return False
        try:
            with open(path, "rb") as f:
                data = pickle.load(f)
            self.model = data["model"]
            self.scaler = data["scaler"]
            self.is_trained = True
            print(f"Model loaded from {path}")
            return True
        except Exception as e:
            print(f"Failed to load model from {path}: {e}. Falling back.")
            return False


def run_ml_optimization(services, dependencies, cves, constraints) -> dict:
    """
    ML-accelerated pipeline: Bayesian -> ML Predictor -> Pareto.
    Drop-in replacement for run_full_optimization when a trained model exists.
    Falls back to Monte Carlo if no model is available.
    """
    from .bayesian import BayesianRiskGraph
    from .pareto import ParetoOptimizer, _generate_diverse_orderings

    # Stage 1: Bayesian Risk Propagation (same as original)
    graph = BayesianRiskGraph(services, dependencies, cves)
    propagated_cves = graph.get_cve_propagated_scores()

    # Stage 2: ML Prediction (replaces Monte Carlo)
    predictor = PatchPriorityPredictor()
    if predictor.load():
        ml_results = predictor.predict_priority(propagated_cves)
    else:
        print("No trained model found. Falling back to Monte Carlo.")
        from .monte_carlo import MonteCarloSimulator
        simulator = MonteCarloSimulator(propagated_cves, constraints, n_iterations=2000)
        ml_results = simulator.simulate()

    # Stage 3: Pareto Optimization (same as original)
    diverse_orderings = _generate_diverse_orderings(propagated_cves, constraints)
    pareto = ParetoOptimizer(propagated_cves, constraints)
    pareto_front = pareto.find_pareto_front(diverse_orderings)
    profiles = pareto.generate_tradeoff_profiles(pareto_front)

    return {
        "bayesian": {
            "prior_risks": graph.prior_risk,
            "posterior_risks": graph.posterior_risk,
            "propagated_cves": propagated_cves,
        },
        "monte_carlo": ml_results,
        "pareto": {
            "front_size": len(pareto_front),
            "profiles": profiles,
        },
    }
